"""Admin API route/message inventory."""

from __future__ import annotations

from core.enums import (
    AdminApiActionClass,
    AdminApiCompatibilityMode,
    AdminApiPermission,
)

from .models import AdminApiRouteInventoryItem


ADMIN_API_ROUTE_INVENTORY: tuple[AdminApiRouteInventoryItem, ...] = (
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="POST /api/v1/orders",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_PLACE,
        permission=AdminApiPermission.ORDER_CREATE,
        idempotency="required",
        approval="required",
        caps="required",
        audit="required",
        shared_method="place_manual_order",
        parity_test="HTTP vs place_order guard/result parity",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/orders",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_order_list",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/orders/{client_order_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_order_detail",
        parity_test="client_order_id identity only",
    ),
    AdminApiRouteInventoryItem(
        module_id="stealth_orders",
        surface="GET /api/v1/stealth/orders",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_stealth_order_list",
        parity_test="read-only stealth lifecycle evidence; no exchange mutation",
    ),
    AdminApiRouteInventoryItem(
        module_id="stealth_orders",
        surface="GET /api/v1/stealth/orders/{stealth_order_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_stealth_order_detail",
        parity_test="stealth_order_id identity with exchange ids as evidence only",
    ),
    AdminApiRouteInventoryItem(
        module_id="stealth_orders",
        surface="POST /api/v1/stealth/orders/{stealth_order_id}/cancel",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_CANCEL,
        permission=AdminApiPermission.ORDER_CANCEL,
        idempotency="required",
        approval="required by current HTTP live-disabled gate",
        caps="required for rate/session controls and exchange-reality reconciliation",
        audit="required",
        shared_method="cancel_stealth_order_by_stealth_order_id",
        parity_test="stealth_order_id identity; no active placement mutation until exchange handling is complete",
    ),
    AdminApiRouteInventoryItem(
        module_id="movement_repricing",
        surface="GET /api/v1/movement-repricing/evidence",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_movement_repricing_evidence",
        parity_test="read-only move/reprice evidence; no exchange mutation",
    ),
    AdminApiRouteInventoryItem(
        module_id="movement_repricing",
        surface="GET /api/v1/movement-repricing/orders/{client_order_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_movement_repricing_order_detail",
        parity_test="client_order_id identity with exchange ids as evidence only",
    ),
    AdminApiRouteInventoryItem(
        module_id="movement_repricing",
        surface="GET /api/v1/movement-repricing/stealth/{stealth_order_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_movement_repricing_stealth_detail",
        parity_test="stealth_order_id identity with runtime claims as evidence only",
    ),
    AdminApiRouteInventoryItem(
        module_id="movement_repricing",
        surface="POST /api/v1/movement-repricing/stealth/{stealth_order_id}/reprice",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_CANCEL,
        permission=AdminApiPermission.ORDER_CANCEL,
        idempotency="required",
        approval="required by current HTTP live-disabled gate",
        caps="required for rate/session controls, mutation claims, and exchange-reality reconciliation",
        audit="required",
        shared_method="reprice_stealth_order_by_stealth_order_id",
        parity_test="stealth_order_id identity; no cooldown clearing or live repricing until exchange handling is complete",
    ),
    AdminApiRouteInventoryItem(
        module_id="futures_perpetuals",
        surface="GET /api/v1/futures/account",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_futures_account",
        parity_test="read-only futures account, margin, collateral, liquidation, funding, and P/L evidence",
    ),
    AdminApiRouteInventoryItem(
        module_id="futures_perpetuals",
        surface="GET /api/v1/futures/positions",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_futures_positions",
        parity_test="position_key identity and futures close-side semantics; no spot inventory rules",
    ),
    AdminApiRouteInventoryItem(
        module_id="futures_perpetuals",
        surface="GET /api/v1/futures/positions/{position_key}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_futures_position_detail",
        parity_test="backend-defined position identity with no order placement or cancellation",
    ),
    AdminApiRouteInventoryItem(
        module_id="guard_risk_policy",
        surface="GET /api/v1/admin/guard-risk-policy",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="read-only evidence only",
        audit="optional read audit",
        shared_method="build_guard_risk_policy",
        parity_test="read-only guard/risk policy evidence; no browser authority or Coinbase read",
    ),
    AdminApiRouteInventoryItem(
        module_id="audit_workbench",
        surface="GET /api/v1/admin/audit-workbench",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_audit_workbench",
        parity_test="cross-module audit evidence only; no Coinbase read or mutation",
    ),
    AdminApiRouteInventoryItem(
        module_id="legacy_dashboard_websocket",
        surface="place_order WebSocket",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_PLACE,
        permission="compatibility policy",
        idempotency="enterprise-gated or compatibility-only",
        approval="enterprise-gated or compatibility-only",
        caps="required",
        audit="required",
        shared_method="place_manual_order",
        parity_test="WebSocket vs HTTP guard/result parity",
        compatibility_mode=AdminApiCompatibilityMode.COMPATIBILITY_ONLY.value,
    ),
    AdminApiRouteInventoryItem(
        module_id="legacy_dashboard_websocket",
        surface="place_hotpoint_test_order WebSocket",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_PLACE,
        permission="compatibility policy",
        idempotency="enterprise-gated or compatibility-only",
        approval="enterprise-gated or compatibility-only",
        caps="required",
        audit="required",
        shared_method="place_hotpoint_test_order",
        parity_test="WebSocket vs shared-service hotpoint guard/result parity",
        compatibility_mode=AdminApiCompatibilityMode.COMPATIBILITY_ONLY.value,
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="POST /api/v1/orders/{client_order_id}/cancel",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_CANCEL,
        permission=AdminApiPermission.ORDER_CANCEL,
        idempotency="required",
        approval="required by current HTTP live-disabled gate",
        caps="required for rate/session controls",
        audit="required",
        shared_method="cancel_order_by_client_order_id",
        parity_test="HTTP vs cancel_order parity",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="POST /api/v1/spot/campaign/executions",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_PLACE,
        permission=AdminApiPermission.CAMPAIGN_EXECUTE,
        idempotency="required",
        approval="required",
        caps="required",
        audit="required",
        shared_method="execute_spot_campaign",
        parity_test="campaign execution remains fail-closed until live gates pass",
    ),
    AdminApiRouteInventoryItem(
        module_id="legacy_dashboard_websocket",
        surface="cancel_order WebSocket",
        action_class=AdminApiActionClass.LIVE_EXCHANGE_CANCEL,
        permission="compatibility policy",
        idempotency="enterprise-gated or compatibility-only",
        approval="not required unless policy adds approval",
        caps="required for rate/session controls",
        audit="required",
        shared_method="cancel_order_by_client_order_id",
        parity_test="WebSocket vs HTTP parity",
        compatibility_mode=AdminApiCompatibilityMode.COMPATIBILITY_ONLY.value,
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/bootstrap",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_admin_bootstrap",
        parity_test="backend association and live-disabled posture",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/approvals",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.APPROVAL_READ,
        idempotency="not required",
        approval="not applicable",
        caps="not applicable",
        audit="optional read audit",
        shared_method="list_approvals",
        parity_test="read-only approval lifecycle evidence; no command execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/approvals/requests/{approval_request_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.APPROVAL_READ,
        idempotency="not required",
        approval="not applicable",
        caps="not applicable",
        audit="optional read audit",
        shared_method="get_approval_request",
        parity_test="approval request identity only; no command execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="POST /api/v1/admin/approvals/requests",
        action_class=AdminApiActionClass.LOCAL_STATE_MUTATION,
        permission=AdminApiPermission.APPROVAL_REQUEST,
        idempotency="required",
        approval="creates request only; not sufficient for live execution",
        caps="not applicable",
        audit="required",
        shared_method="create_approval_request",
        parity_test="request records are backend-owned and append-only",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="POST /api/v1/admin/approvals/requests/{approval_request_id}/decisions",
        action_class=AdminApiActionClass.LOCAL_STATE_MUTATION,
        permission=AdminApiPermission.APPROVAL_MANAGE,
        idempotency="required",
        approval="records backend decision; browser approval remains insufficient",
        caps="not applicable",
        audit="required",
        shared_method="decide_approval_request",
        parity_test="approved decisions link snapshots but do not execute commands",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="POST /api/v1/admin/approvals/{approval_id}/revoke",
        action_class=AdminApiActionClass.LOCAL_STATE_MUTATION,
        permission=AdminApiPermission.APPROVAL_MANAGE,
        idempotency="required",
        approval="revokes backend approval snapshot",
        caps="not applicable",
        audit="required",
        shared_method="revoke_approval",
        parity_test="revoked snapshots fail closed in resolver",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/admission-audits",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ADMISSION_AUDIT_READ,
        idempotency="not required",
        approval="not applicable",
        caps="not applicable",
        audit="read-only admission audit evidence",
        shared_method="list_admission_audits",
        parity_test="read-only admission audits; no command execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/admission-audits/{admission_audit_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ADMISSION_AUDIT_READ,
        idempotency="not required",
        approval="not applicable",
        caps="not applicable",
        audit="read-only admission audit evidence",
        shared_method="get_admission_audit",
        parity_test="admission_audit_id identity only; no command execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="POST /api/v1/admin/admission-audits",
        action_class=AdminApiActionClass.LOCAL_STATE_MUTATION,
        permission=AdminApiPermission.ADMISSION_AUDIT_RECORD,
        idempotency="required",
        approval="required backend approval snapshot id link",
        caps="links expected cap/guard decision ref without evaluating guards",
        audit="required append-only admission audit proof",
        shared_method="record_admission_audit",
        parity_test="records are backend-owned and append-only; no browser audit writer",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/cap-guard/decisions",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.CAP_GUARD_READ,
        idempotency="not required",
        approval="not applicable",
        caps="read-only cap/guard decision evidence",
        audit="optional read audit",
        shared_method="list_cap_guard_decisions",
        parity_test="read-only cap/guard decisions; no guard evaluation or command execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/cap-guard/decisions/{decision_id}",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.CAP_GUARD_READ,
        idempotency="not required",
        approval="not applicable",
        caps="read-only cap/guard decision evidence",
        audit="optional read audit",
        shared_method="get_cap_guard_decision",
        parity_test="decision_id identity only; no guard evaluation or command execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="POST /api/v1/admin/cap-guard/decisions",
        action_class=AdminApiActionClass.LOCAL_STATE_MUTATION,
        permission=AdminApiPermission.CAP_GUARD_RECORD,
        idempotency="required",
        approval="required backend approval snapshot id link",
        caps="records passed or blocked backend cap/guard evidence",
        audit="required",
        shared_method="record_cap_guard_decision",
        parity_test="records are backend-owned and append-only; no browser guard evaluator",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/health",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_admin_health",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/session",
        action_class=AdminApiActionClass.READ_ONLY,
        permission="authenticated actor",
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_admin_session",
        parity_test="backend RBAC evidence only",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/oidc-readiness",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_oidc_jwt_readiness",
        parity_test="backend OIDC verifier readiness evidence only",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/capabilities",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_admin_capabilities",
        parity_test="route inventory derived registry with module_id evidence",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/csrf",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_csrf_contract",
        parity_test="does not disclose token value",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/live-enablement",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="read-only cap evidence only",
        audit="optional read audit",
        shared_method="build_live_enablement",
        parity_test="read-only M8 live-enablement readiness; no Coinbase execution",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/enterprise-readiness",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="read-only release evidence only",
        audit="optional read audit",
        shared_method="build_enterprise_readiness",
        parity_test=(
            "read-only M9/M20/M21 module support, registry, unsupported action, "
            "structured command-gap, security, and release evidence"
        ),
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/release-gate",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_release_gate",
        parity_test="browser does not run pytest",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/recovery-gate",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_recovery_gate",
        parity_test="read-only recovery evidence",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/fill-ledger-health",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_fill_ledger_health",
        parity_test="no ledger repair mutation",
    ),
    AdminApiRouteInventoryItem(
        module_id="admin_system_health",
        surface="GET /api/v1/admin/frontend-fixtures",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_frontend_fixtures",
        parity_test="backend-owned mock fixture examples",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/spot/readiness",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_spot_readiness",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/spot/sweep/status",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_spot_sweep_status",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/spot/sweep/pnl",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_spot_sweep_pnl",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/spot/cost-basis/status",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.ANALYTICS_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_spot_cost_basis_status",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/spot/campaign/status",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.CAMPAIGN_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_spot_campaign_status",
        parity_test="no Coinbase REST placement",
    ),
    AdminApiRouteInventoryItem(
        module_id="spot_operations",
        surface="GET /api/v1/spot/direct-orders/{client_order_id}/audit",
        action_class=AdminApiActionClass.READ_ONLY,
        permission=AdminApiPermission.AUDIT_READ,
        idempotency="not required",
        approval="not required",
        caps="not applicable",
        audit="optional read audit",
        shared_method="build_spot_direct_order_audit",
        parity_test="no Coinbase REST placement",
    ),
)
